"""initial_schema

Revision ID: 01b0e0c43ea4
Revises: 
Create Date: 2026-04-25 13:06:25.917001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01b0e0c43ea4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operator_id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('oauth_provider', sa.String(), nullable=True),
    sa.Column('oauth_id', sa.String(), nullable=True),
    sa.Column('operating_system', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_oauth_id'), 'users', ['oauth_id'], unique=True)
    op.create_index(op.f('ix_users_operator_id'), 'users', ['operator_id'], unique=True)
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_name', sa.String(), nullable=False),
    sa.Column('owner_company', sa.String(), nullable=False),
    sa.Column('match_description', sa.Text(), nullable=True),
    sa.Column('media_file_path', sa.String(), nullable=False),
    sa.Column('scoreboard_file_path', sa.String(), nullable=True),
    sa.Column('scrap_youtube', sa.Boolean(), nullable=True),
    sa.Column('scrap_reddit', sa.Boolean(), nullable=True),
    sa.Column('scrap_instagram', sa.Boolean(), nullable=True),
    sa.Column('total_frames', sa.Integer(), nullable=True),
    sa.Column('audio_fp', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_asset_name'), 'assets', ['asset_name'], unique=False)
    op.create_index(op.f('ix_assets_id'), 'assets', ['id'], unique=False)
    op.create_index(op.f('ix_assets_owner_company'), 'assets', ['owner_company'], unique=False)
    op.create_table('scan_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('search_query', sa.String(), nullable=False),
    sa.Column('platforms', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scan_jobs_id'), 'scan_jobs', ['id'], unique=False)
    op.create_table('asset_frames',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('frame_number', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('phash_value', sa.String(), nullable=True),
    sa.Column('pdq_hash', sa.String(length=64), nullable=True),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_frames_id'), 'asset_frames', ['id'], unique=False)
    op.create_table('scraped_videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_job_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('platform_video_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('local_folder_path', sa.String(), nullable=True),
    sa.Column('frame_paths', sa.JSON(), nullable=True),
    sa.Column('uploader', sa.String(), nullable=True),
    sa.Column('like_count', sa.Integer(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('comments', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['scan_job_id'], ['scan_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scraped_videos_id'), 'scraped_videos', ['id'], unique=False)
    op.create_index(op.f('ix_scraped_videos_platform'), 'scraped_videos', ['platform'], unique=False)
    op.create_index(op.f('ix_scraped_videos_platform_video_id'), 'scraped_videos', ['platform_video_id'], unique=False)
    op.create_table('detection_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scraped_video_id', sa.Integer(), nullable=False),
    sa.Column('matched_asset_id', sa.Integer(), nullable=True),
    sa.Column('phash_score', sa.Float(), nullable=False),
    sa.Column('pdq_score', sa.Float(), nullable=False),
    sa.Column('audio_score', sa.Float(), nullable=False),
    sa.Column('metadata_score', sa.Float(), nullable=False),
    sa.Column('final_score', sa.Float(), nullable=False),
    sa.Column('verdict', sa.String(), nullable=False),
    sa.Column('ai_decision', sa.String(), nullable=True),
    sa.Column('ai_reason', sa.Text(), nullable=True),
    sa.Column('dispatch_status', sa.String(), nullable=False),
    sa.Column('dispatched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['matched_asset_id'], ['assets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scraped_video_id'], ['scraped_videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detection_results_id'), 'detection_results', ['id'], unique=False)
    op.create_index(op.f('ix_detection_results_verdict'), 'detection_results', ['verdict'], unique=False)
    op.create_table('scraped_frames',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('frame_number', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('phash_value', sa.String(), nullable=True),
    sa.Column('pdq_hash', sa.String(length=64), nullable=True),
    sa.Column('scraped_video_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['scraped_video_id'], ['scraped_videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scraped_frames_id'), 'scraped_frames', ['id'], unique=False)
    op.create_table('judge_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('detection_result_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=True),
    sa.Column('decision', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['detection_result_id'], ['detection_results.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('detection_result_id')
    )
    op.create_index(op.f('ix_judge_reviews_decision'), 'judge_reviews', ['decision'], unique=False)
    op.create_index(op.f('ix_judge_reviews_id'), 'judge_reviews', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_judge_reviews_id'), table_name='judge_reviews')
    op.drop_index(op.f('ix_judge_reviews_decision'), table_name='judge_reviews')
    op.drop_table('judge_reviews')
    op.drop_index(op.f('ix_scraped_frames_id'), table_name='scraped_frames')
    op.drop_table('scraped_frames')
    op.drop_index(op.f('ix_detection_results_verdict'), table_name='detection_results')
    op.drop_index(op.f('ix_detection_results_id'), table_name='detection_results')
    op.drop_table('detection_results')
    op.drop_index(op.f('ix_scraped_videos_platform_video_id'), table_name='scraped_videos')
    op.drop_index(op.f('ix_scraped_videos_platform'), table_name='scraped_videos')
    op.drop_index(op.f('ix_scraped_videos_id'), table_name='scraped_videos')
    op.drop_table('scraped_videos')
    op.drop_index(op.f('ix_asset_frames_id'), table_name='asset_frames')
    op.drop_table('asset_frames')
    op.drop_index(op.f('ix_scan_jobs_id'), table_name='scan_jobs')
    op.drop_table('scan_jobs')
    op.drop_index(op.f('ix_assets_owner_company'), table_name='assets')
    op.drop_index(op.f('ix_assets_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_asset_name'), table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_users_operator_id'), table_name='users')
    op.drop_index(op.f('ix_users_oauth_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
