"""add_cascade_delete

Revision ID: 0912aa0a238a
Revises: 01b0e0c43ea4
Create Date: 2026-04-25 14:00:20.778467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0912aa0a238a'
down_revision: Union[str, Sequence[str], None] = '01b0e0c43ea4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('detection_results_matched_asset_id_fkey'), 'detection_results', type_='foreignkey')
    op.create_foreign_key(None, 'detection_results', 'assets', ['matched_asset_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'detection_results', type_='foreignkey')
    op.create_foreign_key(op.f('detection_results_matched_asset_id_fkey'), 'detection_results', 'assets', ['matched_asset_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
