"""add metadata fields

Revision ID: 47913c25f5e7
Revises: c4d8f43e7f77
Create Date: 2026-04-24 17:45:20.221786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47913c25f5e7'
down_revision: Union[str, Sequence[str], None] = 'c4d8f43e7f77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detection_results', sa.Column('metadata_score', sa.Float(), nullable=True))
    op.execute("UPDATE detection_results SET metadata_score = 0.0")
    op.alter_column('detection_results', 'metadata_score', nullable=False)
    op.add_column('scraped_videos', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scraped_videos', 'description')
    op.drop_column('detection_results', 'metadata_score')
    # ### end Alembic commands ###
