"""add_rich_metadata_to_scraped_videos

Revision ID: 70173bded4bf
Revises: 47913c25f5e7
Create Date: 2026-04-24 19:55:27.427434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70173bded4bf'
down_revision: Union[str, Sequence[str], None] = '47913c25f5e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scraped_videos', sa.Column('uploader', sa.String(), nullable=True))
    op.add_column('scraped_videos', sa.Column('like_count', sa.Integer(), nullable=True))
    op.add_column('scraped_videos', sa.Column('view_count', sa.Integer(), nullable=True))
    op.add_column('scraped_videos', sa.Column('comments', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scraped_videos', 'comments')
    op.drop_column('scraped_videos', 'view_count')
    op.drop_column('scraped_videos', 'like_count')
    op.drop_column('scraped_videos', 'uploader')
    # ### end Alembic commands ###
