"""add_asset_frames_and_total_frames

Revision ID: 7e9fec7312e3
Revises: 29b654861f9b
Create Date: 2026-04-23 07:58:12.919995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e9fec7312e3'
down_revision: Union[str, Sequence[str], None] = '29b654861f9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_frames',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('frame_number', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('phash_value', sa.String(), nullable=True),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_frames_id'), 'asset_frames', ['id'], unique=False)
    op.add_column('assets', sa.Column('total_frames', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'total_frames')
    op.drop_index(op.f('ix_asset_frames_id'), table_name='asset_frames')
    op.drop_table('asset_frames')
    # ### end Alembic commands ###
