"""Add frame_paths to scraped_videos

Revision ID: c4d8f43e7f77
Revises: f55b704ce9ca
Create Date: 2026-04-24 17:15:12.743542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4d8f43e7f77'
down_revision: Union[str, Sequence[str], None] = 'f55b704ce9ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scraped_videos', sa.Column('frame_paths', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scraped_videos', 'frame_paths')
    # ### end Alembic commands ###
