"""add_audio_storage_columns

Revision ID: e86b38cdd8e5
Revises: 0912aa0a238a
Create Date: 2026-04-26 01:33:33.655273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e86b38cdd8e5'
down_revision: Union[str, Sequence[str], None] = '0912aa0a238a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scraped_videos', sa.Column('audio_url', sa.String(), nullable=True))
    op.add_column('scraped_videos', sa.Column('audio_fp', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scraped_videos', 'audio_fp')
    op.drop_column('scraped_videos', 'audio_url')
    # ### end Alembic commands ###
