"""add_scraped_frames_table

Revision ID: f55b704ce9ca
Revises: fffa04d7fc14
Create Date: 2026-04-23 10:45:21.565222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f55b704ce9ca'
down_revision: Union[str, Sequence[str], None] = 'fffa04d7fc14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scraped_frames',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('frame_number', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('phash_value', sa.String(), nullable=True),
    sa.Column('pdq_hash', sa.String(length=64), nullable=True),
    sa.Column('scraped_video_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['scraped_video_id'], ['scraped_videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scraped_frames_id'), 'scraped_frames', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scraped_frames_id'), table_name='scraped_frames')
    op.drop_table('scraped_frames')
    # ### end Alembic commands ###
