"""Add detection and pipeline models

Revision ID: fffa04d7fc14
Revises: 7e9fec7312e3
Create Date: 2026-04-23 08:43:10.758378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fffa04d7fc14'
down_revision: Union[str, Sequence[str], None] = '7e9fec7312e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scan_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('search_query', sa.String(), nullable=False),
    sa.Column('platforms', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scan_jobs_id'), 'scan_jobs', ['id'], unique=False)
    op.create_table('scraped_videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_job_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('platform_video_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('local_folder_path', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['scan_job_id'], ['scan_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scraped_videos_id'), 'scraped_videos', ['id'], unique=False)
    op.create_index(op.f('ix_scraped_videos_platform'), 'scraped_videos', ['platform'], unique=False)
    op.create_index(op.f('ix_scraped_videos_platform_video_id'), 'scraped_videos', ['platform_video_id'], unique=False)
    op.create_table('detection_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scraped_video_id', sa.Integer(), nullable=False),
    sa.Column('matched_asset_id', sa.Integer(), nullable=True),
    sa.Column('phash_score', sa.Float(), nullable=False),
    sa.Column('pdq_score', sa.Float(), nullable=False),
    sa.Column('audio_score', sa.Float(), nullable=False),
    sa.Column('final_score', sa.Float(), nullable=False),
    sa.Column('verdict', sa.String(), nullable=False),
    sa.Column('ai_decision', sa.String(), nullable=True),
    sa.Column('ai_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['matched_asset_id'], ['assets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scraped_video_id'], ['scraped_videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detection_results_id'), 'detection_results', ['id'], unique=False)
    op.create_index(op.f('ix_detection_results_verdict'), 'detection_results', ['verdict'], unique=False)
    op.create_table('judge_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('detection_result_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=True),
    sa.Column('decision', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['detection_result_id'], ['detection_results.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('detection_result_id')
    )
    op.create_index(op.f('ix_judge_reviews_decision'), 'judge_reviews', ['decision'], unique=False)
    op.create_index(op.f('ix_judge_reviews_id'), 'judge_reviews', ['id'], unique=False)
    op.add_column('asset_frames', sa.Column('pdq_hash', sa.String(length=64), nullable=True))
    op.add_column('assets', sa.Column('audio_fp', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'audio_fp')
    op.drop_column('asset_frames', 'pdq_hash')
    op.drop_index(op.f('ix_judge_reviews_id'), table_name='judge_reviews')
    op.drop_index(op.f('ix_judge_reviews_decision'), table_name='judge_reviews')
    op.drop_table('judge_reviews')
    op.drop_index(op.f('ix_detection_results_verdict'), table_name='detection_results')
    op.drop_index(op.f('ix_detection_results_id'), table_name='detection_results')
    op.drop_table('detection_results')
    op.drop_index(op.f('ix_scraped_videos_platform_video_id'), table_name='scraped_videos')
    op.drop_index(op.f('ix_scraped_videos_platform'), table_name='scraped_videos')
    op.drop_index(op.f('ix_scraped_videos_id'), table_name='scraped_videos')
    op.drop_table('scraped_videos')
    op.drop_index(op.f('ix_scan_jobs_id'), table_name='scan_jobs')
    op.drop_table('scan_jobs')
    # ### end Alembic commands ###
